#.travis.yml
sudo: false

dist: trusty

language: node_js

node_js:
  - $FIREBASE_NODE_VER

install:
  - yarn install
  - cd $TRAVIS_BUILD_DIR/functions && yarn install

script:
  - cd $TRAVIS_BUILD_DIR
  - echo $TRAVIS_NODE_VERSION
  - yarn test
  - yarn build

before_deploy:
  - npm install -g firebase-tools

deploy:
  # production deploy
  - provider: script
    skip_cleanup: true
    script: firebase deploy --project $FIREBASE_PROJECT --token $FIREBASE_TOKEN --non-interactive
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH = "master" && $TRAVIS_NODE_VERSION = $FIREBASE_NODE_VER

  # staging deploy
  - provider: script
    skip_cleanup: true
    script: firebase deploy -f --project $FIREBASE_DEV_PROJECT --token $FIREBASE_DEV_TOKEN --non-interactive
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH = "feature/add-travis-ci" && $FIREBASE_DEV_DEPLOY = "true" && $TRAVIS_NODE_VERSION = $FIREBASE_NODE_VER

cache:
    npm: true
    directories:
        - node_modules
        - functions/node_modules