#.travis.yml
sudo: false

dist: trusty

language: node_js

node_js:
  - 8

install:
  - yarn install
  - cd $TRAVIS_BUILD_DIR/functions && yarn install && cd $TRAVIS_BUILD_DIR

cache:
    npm: true
    directories:
        - node_modules
        - functions/node_modules