language: node_js

node_js:
  - "node"

script:
  -

deploy:
  provider: firebase
  token:
    secure: 1//0ebbuXgxDc8mICgYIARAAGA4SNwF-L9IrPJIlky6vMrJFXrRKqBoJ6NSWqPQILayMr8cJ78Low9ESLIvHR8_2PAvY-1QLIaEmdiw
  project: test-hosting-f43e9
