#.travis.yml
sudo: false

dist: trusty

language: node_js

node_js:
  - 8

install:
  - npm install
  - cd $TRAVIS_BUILD_DIR/functions
  - npm install

cache:
    npm: true
    directories:
        - node_modules
        - functions/node_modules