#.travis.yml
sudo: false

dist: trusty

language: node_js

node_js:
  - $FIREBASE_NODE_VER

install:
  - yarn install
  - cd $TRAVIS_BUILD_DIR/functions && yarn install && cd $TRAVIS_BUILD_DIR

before_deploy:
  - npm install -g firebase-tools

deploy:
  - provider: script
    skip_cleanup: true
    script: firebase deploy --project $FIREBASE_PROJECT --token $FIREBASE_TOKEN --non-interactive
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH = "master" && $TRAVIS_NODE_VERSION = $FIREBASE_NODE_VER

cache:
    npm: true
    directories:
        - node_modules
        - functions/node_modules