deploy:
  provider: firebase
  token:
    secure: 1//0ebbuXgxDc8mICgYIARAAGA4SNwF-L9IrPJIlky6vMrJFXrRKqBoJ6NSWqPQILayMr8cJ78Low9ESLIvHR8_2PAvY-1QLIaEmdiw
  project: test-hosting-f43e9

env:
  global:
    secure: MumswUvXQzkEm1VOyAQ7i6xoQgQI8LiDahwv4eCwk5ADsvEJB/X2b+yruzHclZwXGVnEea3mK4j/oz1/F0ctG9PB7ceWjIY2pYYs+ScFiF6cyytHpdEYmSdPXiBdFlO7tzx2GRrEFl/gBIxm5GQaeZyAujrfQWC9Qikd2ErlKPN6fFbUwem7S7NkQpxR3K15IRRIc5DkRU8GFzWsZmheM+6A4Nr93RAIrcXpViDfcmgpOX0Xq4afjVAIZfoljDdI9lyNYGh19yQu04JM93vEdEtAA2WkoshTr9RJuRswRhHinDorxOZ3d9Ny2z3OqGbBp6V1l2ubmen7eDgdEHqv5Jw2juqFrcrWJk6zcgTXrfiGnJdxvay7+iVuyElbbh9mdIZAuf1DODyVZKholGgrj2gnzX6K7I9IfEX7yeoJCezSn9724lUCAOZZmfHEibJHBIh9ZMiiqYNW4JHM6BSDUr4gl/AoiSxVGXKgZ9vus17+JQI7pyPUyMDa689wzFYkWhPd/DxN+IP+6lzD+CthExcFDHN0LWPe6rgTQX0679j0fJjTnoKM9IMVWchISvM/iYzubiNpXBDgDO3VfNf7nO7pewH8AG6GDv95O4B+ldP21pC18S3IRZXra4CDqWGxwz6D6xFr+g+R2/8UFt8RP3s/vcaM1AfbSld4Qe87RzY=
